/*
 * This source file was generated by the Gradle 'init' task
 */
package io.grahl

import io.grahl.analyzer.dependencies.Dependency
import io.grahl.analyzer.framework.Framework
import io.grahl.analyzer.framework.FrameworkAnalyzer
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test fun `should detect framework`() {
        val dependencies = listOf(
            Dependency("spring.io", "org.springframework", "Spring", "2.0"),
            Dependency("nextjs.com", "@next-js", "next js", "2.1.3"),
            Dependency("bun.sh", "@bun", "bun", "2.1.3")
        )

        val result = FrameworkAnalyzer().findFramework(dependencies)

        assertTrue { result.size == 2 }
    }
}
